### ISSUE TITLE
error: reference to 'RGB' is ambiguous

### ISSUE THREAD

**Issue by GeertWille** [focalintent/FastLED-Sparkcore#1]
When trying to use the RGB led on the SparkCore in combination with the library you get errors because of a naming collision.

```NSFastLED::EOrder RGB```
and
```RGBClass RGB```

**Comment by focalintent** [comment]
In that case, take out the FASTLED_USING_NAMESPACE declaration and explicitly namespace all your references to FastLED functions/constants/etc...

**Comment by GeertWille** [comment]
Thanks!
