### ISSUE TITLE
FastLED.h: No such file or directory  #include "FastLED.h"

### ISSUE THREAD

**Issue by suhajdab** [focalintent/FastLED-Sparkcore#17]
A script compiled without issues a few days ago, now throws this at me: ```lib/FastLED2/examples/FirstLight/FirstLight.ino:6:21: fatal error: FastLED.h: No such file or directory
 #include "FastLED.h"```

Anyone know what happened? Something at particle.io?

**Comment by suhajdab** [comment]
Found the answer: "You need to set the build target version to 0.6.2 (any 0.5.3+ should also work, but why stick with "buggy" versions?)"
https://community.particle.io/t/library-include-error-web-ide/35605

**Comment by robojax** [comment]
Hi @suhajdab  what do you mean "set target". where and how? is it referring to hardware setting or something in the code?
