### ISSUE TITLE
Firmware 0.4.9 SPI definition broken.

### ISSUE THREAD

**Issue by Jerware** [focalintent/FastLED-Sparkcore#8]
In Particle firmware 0.4.9, SPI was changed from a global instance to a #define to ensure that it is initialized before use. This results in 30+ compile errors in chipsets.h complaining that "mSPI was not declared in this scope."

See the following for a discussion and quick-fix workaround from Particle.
https://community.particle.io/t/issues-with-0-4-9-firmware/19466/10?u=jerware

**Comment by focalintent** [comment]
They've undone their change causing this break.
